### ISSUE TITLE
Check on this if again 

### ISSUE THREAD

**Issue by mayisa87** [Layusmen/RefactorSlotMAchine#11]
https://github.com/Layusmen/RefactorSlotMAchine/blob/ef85ab1e2b65660f0eaa3ac1b1cabfdb87f1f8d2/RefactorSlotMachine/logics.cs#L90-L96

Imagine that your first two lines match and third one not. The boolean variable will be false therefore, even if you had a match. So I'm not sure if this is really working. 

To best test your slot machine, you can return an hardcoded int array with the values you need for testing from your filling method. 
Therefore, first fix issue #8!

So instead of returning the array filled with the random numbers, you can for testing just overwrite it and use like:

array =  new char[,] { { '1','1','1'},
                                               {'1','1','1' },
                                               {'1','1','1' }     };

**Comment by Layusmen** [comment]
Except I don't understand what you mean. I have tested the code as suggested and everything is working fine.
