### ISSUE TITLE
Don't mix ui and logic!

### ISSUE THREAD

**Issue by incredibleLeitman** [Layusmen/RefactorSlotMAchine#26]
https://github.com/Layusmen/RefactorSlotMAchine/blob/14f66440d29edaaa6e986aa72ff31ca779650513/RefactorSlotMachine/UIMethods.cs#L52-L75

This function does 2 things at the same time: create/fill a char array (which is a logic part) 
and print it to the console (which is ui related)
-> thus should be split into 2 separate functions

**Comment by incredibleLeitman** [comment]
This is not fixed yet 👆 

You seem to just have moved the whole function to your logic functions
https://github.com/Layusmen/RefactorSlotMAchine/blob/66d1f1e9cc462ea085d1186cb18d5b5ee61bebf8/RefactorSlotMachine/logics.cs#L358-L373
which is now even wrongly named and contains a Console.WriteLine

The way to solve this is to split this function into two:
- one that creates/fills the grid in your logic class
- and one that prints each cell of the grid to the console in your ui class

**Comment by Layusmen** [comment]
I was told

> This is not fixed yet 👆
> 
> You seem to just have moved the whole function to your logic functions
> 
> https://github.com/Layusmen/RefactorSlotMAchine/blob/66d1f1e9cc462ea085d1186cb18d5b5ee61bebf8/RefactorSlotMachine/logics.cs#L358-L373
> 
> which is now even wrongly named and contains a Console.WriteLine
> 
> The way to solve this is to split this function into two:
> 
>     * one that creates/fills the grid in your logic class
> 
>     * and one that prints each cell of the grid to the console in your ui class

I was told to change the name: https://github.com/Layusmen/RefactorSlotMAchine/issues/38
