### ISSUE TITLE
Combine to one function

### ISSUE THREAD

**Issue by incredibleLeitman** [Layusmen/RefactorSlotMAchine#28]
https://github.com/Layusmen/RefactorSlotMAchine/blob/14f66440d29edaaa6e986aa72ff31ca779650513/RefactorSlotMachine/Program.cs#L51-L59
Remember, we do not want any Console.X calls elsewhere than the ui methods class 👆 
Here you call a ui method, that just prints the user prompt, 
but then read and evaluate user input (which should be in a ui method)

--> instead you should have one ui function that prints to the user what to enter, accepts user input and
either return the value directly to check from the main
or return the already evaluated value (like return "true" when the entered key equals one of the YES options)

**Comment by incredibleLeitman** [comment]
Why did you lost the use of constants in this change? 🤔 
https://github.com/Layusmen/RefactorSlotMAchine/blob/66d1f1e9cc462ea085d1186cb18d5b5ee61bebf8/RefactorSlotMachine/UIMethods.cs#L68

Before you had
```playAgain = key.KeyChar == Constants.SMALLYES || key.KeyChar == Constants.CAPITALYES; ```

**Comment by Layusmen** [comment]
Corrected!
