### ISSUE TITLE
Method is called but return value is never assigned

### ISSUE THREAD

**Issue by AlexKap23** [Layusmen/RefactorSlotMAchine#5]
https://github.com/Layusmen/RefactorSlotMAchine/blob/f59bf2f12096d25edc6400e62b8fe3bc8301dc18/RefactorSlotMachine/Program.cs#L29

Your methods are returning back an decimal but the value is never assigned to the balance variable on your Program.cs. As a result this variable is constantly having the same value, no matter what the player does, winning or loosing.

**Comment by mayisa87** [comment]
This is OK now, you return it. Next step is issue #13
